name: deploy-container

on:
  push:
    branches:
      - master
    paths:
      - "_container/**"

defaults:
  run:
    working-directory: _container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
